language: java
jdk: openjdk8
dist: xenial
install:
  - curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip --output $HOME/android-sdk.zip
  - unzip -qq $HOME/android-sdk.zip -d $HOME/android-sdk
  - export ANDROID_SDK_HOME=$HOME/android-sdk
  - export ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndk/20.1.5948944
  - function installAndroidComponent() { yes | ${ANDROID_SDK_HOME}/tools/bin/sdkmanager $1 > /dev/null; }
  - installAndroidComponent "ndk;20.1.5948944"
  - installAndroidComponent "patcher;v4"
  - installAndroidComponent "cmake;3.10.2.4988404"
  # Keeping track of the NDK version that was used
  - cat $ANDROID_NDK_HOME/source.properties
  # Installing meson for libdav1d building
  - sudo apt-get install nasm python3-pip python3-setuptools python3-wheel ninja-build
  - sudo pip3 install meson
  - curl http://archive.ubuntu.com/ubuntu/pool/universe/n/nasm/nasm_2.13.02-0.1_amd64.deb --output nasm_2.13.02-0.1_amd64.deb
  - sudo dpkg -i nasm_2.13.02-0.1_amd64.deb
  # - sudo apt-get update
  # - sudo apt-get upgrade
  # - sudo apt-get install dpkg
script:
  - bash -e ffmpeg-android-maker.sh --enable-libdav1d --enable-libmp3lame --enable-libaom
